import RPi.GPIO as GPIO

WINNER_WHITE_LED_PIN = 5
WINNER_BLACK_LED_PIN = 6
WINNER_DRAW_LED_PIN = 7
STATE_PLAYING_LED_PIN = 8
STATE_PAUSED_LED_PIN = 9
STATE_FINISHED_LED_PIN = 10
SIDE_WHITE_LED_PIN = 11
SIDE_BLACK_LED_PIN = 25

CALIBRATE_BUTTON_PIN = 22
SIDE_BUTTON_PIN = 23
START_BUTTON_PIN = 24
STOP_BUTTON_PIN = 27

GPIO.setmode(GPIO.BCM)

GPIO.setup(WINNER_WHITE_LED_PIN, GPIO.OUT)
GPIO.setup(WINNER_BLACK_LED_PIN, GPIO.OUT)
GPIO.setup(WINNER_DRAW_LED_PIN, GPIO.OUT)
GPIO.setup(STATE_PLAYING_LED_PIN, GPIO.OUT)
GPIO.setup(STATE_PAUSED_LED_PIN, GPIO.OUT)
GPIO.setup(STATE_FINISHED_LED_PIN, GPIO.OUT)
GPIO.setup(SIDE_WHITE_LED_PIN, GPIO.OUT)
GPIO.setup(SIDE_BLACK_LED_PIN, GPIO.OUT)

GPIO.setup(CALIBRATE_BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(SIDE_BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(START_BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(STOP_BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

GPIO.cleanup()
